version: '3.8'

services:
  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://database:27017/mydb
    depends_on:
      - database

  database:
    image: mongo:latest
    container_name: database
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
