name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH ile EC2'ye bağlan ve deploy et
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /Users/furkanaslan/Desktop/furkantask/
            docker-compose pull
            docker-compose up -d

